# Generated by Django 4.0.6 on 2022-10-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='body',
        ),
    ]
