# Generated by Django 4.0.6 on 2022-10-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_comment_like_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='body',
            new_name='comment',
        ),
    ]
