# Generated by Django 4.0.6 on 2022-11-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_body_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated',
        ),
    ]
