# Generated by Django 4.0.6 on 2023-02-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment_user_likes_like_alreadyliked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosRank', models.IntegerField(null=True)),
                ('Player', models.CharField(max_length=200, null=True)),
                ('Tm', models.CharField(max_length=200, null=True)),
                ('FantPos', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('G', models.IntegerField(null=True)),
                ('GS', models.IntegerField(null=True)),
                ('Rushing_Att', models.IntegerField(null=True)),
                ('Rushing_Yds', models.IntegerField(null=True)),
                ('Rushing_YA', models.FloatField(null=True)),
                ('Rushing_TD', models.IntegerField(null=True)),
                ('Receiving_Tgt', models.IntegerField(null=True)),
                ('Receiving_Rec', models.IntegerField(null=True)),
                ('Receiving_Yds', models.IntegerField(null=True)),
                ('Receiving_YR', models.FloatField(null=True)),
                ('Receiving_TD', models.IntegerField(null=True)),
                ('Fmb', models.IntegerField(null=True)),
                ('FL', models.IntegerField(null=True)),
                ('Total_TD', models.IntegerField(null=True)),
                ('FantPt', models.FloatField(null=True)),
                ('PPR', models.FloatField(null=True)),
                ('VBD', models.FloatField(null=True)),
                ('OvRank', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
