# Generated by Django 4.0.6 on 2023-02-19 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_stats_remove_comment_likes_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='FantPt',
            new_name='fant_pts',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='FL',
            new_name='fmb_loss',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='G',
            new_name='game_started',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='GS',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='OvRank',
            new_name='overall_rank',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='PosRank',
            new_name='pos_rank',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='FantPos',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='PPR',
            new_name='ppr',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Receiving_Rec',
            new_name='receiving_rec',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Receiving_TD',
            new_name='receiving_td',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Receiving_Tgt',
            new_name='receiving_tgt',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Receiving_Yds',
            new_name='receiving_yds',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Receiving_YR',
            new_name='receiving_yr',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Rushing_Att',
            new_name='rushing_att',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Rushing_TD',
            new_name='rushing_td',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Rushing_YA',
            new_name='rushing_ya',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Rushing_Yds',
            new_name='rushing_yds',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Tm',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='Total_TD',
            new_name='total_td',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='VBD',
            new_name='vbd',
        ),
    ]
