# Generated by Django 4.0.6 on 2023-02-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_age_stats_age_rename_fantpt_stats_fant_pts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='fmb_loss',
            new_name='FL',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='position',
            new_name='FantPos',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='fant_pts',
            new_name='FantPt',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='game_started',
            new_name='G',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='games',
            new_name='GS',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='overall_rank',
            new_name='OvRank',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='ppr',
            new_name='PPR',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='pos_rank',
            new_name='PosRank',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='receiving_rec',
            new_name='Receiving_Rec',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='receiving_td',
            new_name='Receiving_TD',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='receiving_tgt',
            new_name='Receiving_Tgt',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='receiving_yr',
            new_name='Receiving_YR',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='receiving_yds',
            new_name='Receiving_Yds',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='rushing_att',
            new_name='Rushing_Att',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='rushing_td',
            new_name='Rushing_TD',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='rushing_ya',
            new_name='Rushing_YA',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='rushing_yds',
            new_name='Rushing_Yds',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='team',
            new_name='Tm',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='total_td',
            new_name='Total_TD',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='vbd',
            new_name='VBD',
        ),
    ]
