# Generated by Django 4.0.6 on 2023-02-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_age_stats_age_rename_fmb_loss_stats_fl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='OvRank',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='VBD',
        ),
    ]
